cluster:
  children:
    server:
      hosts:
        olympus-hecate:
          # ansible_host: 127.0.0.1
        olympus-phobos:
          # ansible_host: 127.0.0.1
        olympus-zephyr:
          # ansible_host: 127.0.0.1
    agent:
      hosts:
        olympus-uranus:
          # ansible_host: 127.0.0.1
  vars:
    ansible_user: root
    k3s_version: v1.31.3+k3s1
