---
name: Linters

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@v4
      - name: 🚀 Run yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@v4
      - name: 🚀 Run shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

  shfmt:
    name: shfmt
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@v4
      - name: 🚀 Run shfmt
        uses: reviewdog/action-shfmt@v1
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@v4
      - name: 🚀 Run markdownlint
        uses: reviewdog/action-markdownlint@v0
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

  ansible-lint:
    name: ansible-lint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@v4
      - name: 🚀 Run ansible-lint
        uses: reviewdog/action-ansiblelint@v1
        with:
          # renovate: datasource=pypi depName=ansible-lint
          ansiblelint_version: 24.10.0
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
